version: '2'
services:
  jhipsterlintestgateway-mongodb:
    image: mongo:4.2.3
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/jhipsterlintestgateway/mongodb/:/data/db/
